# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    networks:
      - mongo_network
    environment:
      MONGO_INITDB_DATABASE: mongo
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    ports:
      - 7072:8081
    networks:
      - mongo_network
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo-mongo-1:27017
      
networks:
  mongo_network: